# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='graphs')),
            ],
            options={
                'db_table': 'my_graph',
                'verbose_name': 'graph',
                'verbose_name_plural': 'graphes',
            },
        ),
    ]
