# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grape', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphmodel',
            options={'ordering': ('-modify_date',), 'verbose_name': 'graph', 'verbose_name_plural': 'graphes'},
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='TITLE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphmodel',
            name='graph',
            field=models.ImageField(upload_to='image'),
        ),
    ]
