# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileUp', '0004_auto_20170112_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='descrption'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
