# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUp', '0002_auto_20170112_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilemodel',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelTable(
            name='uploadfilemodel',
            table='UploadFileModel',
        ),
    ]
