# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUp', '0003_auto_20170112_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfilemodel',
            table='my_document',
        ),
    ]
